- civil_society_vote/accounts/templates/account-base.html
- civil_society_vote/accounts/templates/avatar/change.html
- civil_society_vote/accounts/templates/change-email.html
- civil_society_vote/accounts/templates/partials/sections.html
- civil_society_vote/accounts/templates/password-reset.html
- civil_society_vote/hub/templates/candidate/base.html
- civil_society_vote/hub/templates/candidate/detail.html
- civil_society_vote/hub/templates/header.html
- civil_society_vote/hub/templates/ngo/detail.html
- civil_society_vote/hub/templatetags/hub_tags.py
- civil_society_vote/hub/views.py
- Fix document view permissions in org lists.
- Fix org and candidate list permissions. For some reason
django-guardian does not handle ListView well.
- Make user settings look in line with the other tabbed menus.
Closes #150
> Consolidate committee and staff groups permissions

- civil_society_vote/hub/templates/home.html
- civil_society_vote/static/css/home/alegeri-inscriere.css
> align title to text

- civil_society_vote/static/css/footer.css
Closes #128
Align links in footer
> align footer items

- civil_society_vote/hub/forms.py
- civil_society_vote/hub/templates/contact.html
- civil_society_vote/hub/templates/partials/social_sharing.html
> Add rel="noopener noreferrer" to target blank links

- civil_society_vote/hub/templates/footer.html
- civil_society_vote/static/css/footer.css
Made the footer logo centered and changed the logo text
Closes #148
> Changed the footer logo to be centered

- civil_society_vote/hub/templates/partials/ces_header.html
Changed text and button according to ticket
Closes #144
> Changed text for CES page

- civil_society_vote/hub/templates/registration/login.html
- civil_society_vote/static/css/home/alegeri-jumbotron.css
> mobile styling fixes

- civil_society_vote/hub/views.py
> Prevent unauthorized access to pending/rejected org/candidate

- civil_society_vote/hub/forms.py
- civil_society_vote/hub/templates/candidate/update.html
- civil_society_vote/hub/views.py
> Disable candidate update/revoke if candidate registration flag disabled

- civil_society_vote/hub/templates/committee/candidates.html
- civil_society_vote/hub/views.py
> Add number of supporters in committee candidate list and order by it

- civil_society_vote/hub/admin.py
- civil_society_vote/hub/views.py
> Show only accepted candidates on the candidate list

- civil_society_vote/hub/admin.py
- civil_society_vote/hub/management/commands/seed.py
Based on schedule described here: https://docs.google.com/spreadsheets/d/1LZ9Bi_Z0WSUeAlnBCzOILANtzYr6DQbyC6UA3gvW93c/edit#gid=0
> Add quick action utility for admin to change flags

- civil_society_vote/hub/templates/candidate/detail.html
> Hide support/confirm/vote buttons to superadmin

- civil_society_vote/civil_society_vote/settings/dev.py
- civil_society_vote/hub/utils.py
> Add email header `X-SES-CONFIGURATION-SET`

- civil_society_vote/hub/templates/home.html
- civil_society_vote/hub/templates/rules.html
> Update Methodology according to SGG

- civil_society_vote/hub/templates/ngo/list.html
- civil_society_vote/hub/views.py
> Add NGO counter feature to public list

- civil_society_vote/hub/admin.py
- civil_society_vote/hub/forms.py
> Fix unique email

- civil_society_vote/hub/templates/partials/ces_header.html
- civil_society_vote/hub/templates/terms_and_conditions.html
- civil_society_vote/locale/en/LC_MESSAGES/django.po
- civil_society_vote/locale/ro/LC_MESSAGES/django.po
> Update vote notice

- civil_society_vote/hub/templates/candidate/detail.html
- civil_society_vote/hub/templatetags/hub_tags.py
> Add check if user can't vote

- civil_society_vote/hub/templates/candidate/results.html
> Change winner title

- civil_society_vote/hub/templates/candidate/results.html
- civil_society_vote/hub/templates/partials/ces_header.html
- civil_society_vote/hub/templates/partials/ces_results_header.html
- civil_society_vote/hub/urls.py
> Add caching per view

- civil_society_vote/hub/templates/candidate/results.html
- civil_society_vote/hub/templates/home.html
- civil_society_vote/hub/templates/partials/ces_header.html
- civil_society_vote/hub/templates/partials/ces_results_header.html
> Add final results

- civil_society_vote/civil_society_vote/urls.py
- civil_society_vote/hub/templates/comittee_statement.html
> Add Comittee public statement

- civil_society_vote/civil_society_vote/middleware.py
- civil_society_vote/civil_society_vote/settings/base.py
> Make login case insensitive

- Makefile
- civil_society_vote/hub/views.py
- pyproject.toml
- requirements-dev.txt
- requirements.txt
> Set noindex header for search results page

- civil_society_vote/hub/templates/committee/candidates.html
- civil_society_vote/hub/templates/committee/list.html
- civil_society_vote/hub/views.py
Fixes progress bar regression introduced by the previous commit
Fixes missing rejected candidates counter in the org menu
> Fixes progress bar regression

- civil_society_vote/hub/templates/footer.html
- civil_society_vote/hub/templates/header.html
- civil_society_vote/static/css/footer.css
> [feature/footer] Configure footer layout

- .editorconfig
- civil_society_vote/hub/templates/footer.html
- civil_society_vote/hub/templates/home.html
- civil_society_vote/hub/templates/rules.html
> pnrr updates: rules and title

- docker/s6-rc.d/backend/run
> Change the run script

- backend/hub/social_adapters.py
- act on creating the organization depending on the user type
> Improve the NGO Hub data retrieval

- backend/accounts/forms.py
- backend/accounts/models.py
- backend/accounts/templates/accounts/partials/sections.html
- backend/accounts/views.py
- backend/civil_society_vote/settings.py
- backend/hub/admin.py
- backend/hub/management/commands/init.py
- backend/hub/management/commands/seed.py
- backend/hub/models.py
- backend/hub/social_adapters.py
- backend/hub/templates/hub/candidate/detail.html
- backend/hub/templates/hub/candidate/results.html
- backend/hub/templates/hub/committee/candidates.html
- backend/hub/templates/hub/committee/partials/nav.html
- backend/hub/templates/hub/header.html
- backend/hub/templatetags/hub_tags.py
- backend/hub/views.py
- backend/hub/workers/update_organization.py
Move several template tag computations to the views/models
> Refactor template tags

- backend/locale/ro/LC_MESSAGES/django.po
> Update voting domain warning

- backend/hub/forms.py
- backend/hub/models.py
- backend/hub/templates/hub/candidate/update.html
- backend/hub/views.py
- backend/static_extras/css/hub.css
- make the proposal button more visible
- check that the organization and candidates are complete
> Improve the validation for a candidate proposal
